apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    run: mysql
spec:
  type: ClusterIP
  ports:
  - name: mysql-port
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    db: mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    db: mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mysql-deployment
  labels:
    db: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        db: mysql
    spec:
      containers:
      - name:  mysql
        image:  mysql:5.7
        env:
        - name:  MYSQL_ROOT_PASSWORD
          value:  'Drowssap1!'
        - name:  MYSQL_PASSWORD
          value:  'Drowssap1!!'
        - name:  MYSQL_USER
          value:  'wordpressuser'
        - name:  MYSQL_DATABASE
          value:  'wordpressdb'
        ports:
        - name:  mysql-port
          containerPort:  3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim