name: sync-code

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        run: |
          git clone https://github.com/shefeg/kubernetes_wp.git
          git clone https://github.com/shefeg/kubernetes_wp_clone.git
          cd kubernetes_wp_clone/
          ls -la
          git config --global user.email "gitlab-ci@example.com"
          git config --global user.name "GitLab CI"
          cd ../
          rsync -avh kubernetes_wp/ kubernetes_wp_clone/ --delete
          cd kubernetes_wp_clone/
          echo "kubernetes_wp_clone content"
          ls -la
          git status
          echo "Adding files"
          git add .
          git status
          git commit -m "changes for $(date +%F)"
          git status
          git push -f